### ISSUE TITLE
commission for employee

### ISSUE THREAD

**Issue by mgkhayat** [OCA/commission#1]
I have looked at the commissions video and it is done for an external (not an employee) agent. When I tried an employee agent it asked for a partner and continued as if the agent is not an employee. How does it work for an employee agent?

**Comment by noreiller** [comment]
Hi, I would like to know if there is a workaround to connect an employee to a sale agent.
When creating a sale agent, we are asked to create a new partner, but it would be great to connect it to an existing partner. Because each employee has an associated partner.

**Comment by max3903** [comment]
When you create a user, it creates a partner. Use this partner to check the "Agent" box on it.
When you create the employee, link it with the user created before.
Then you can set the agent as an internal salesman, the employee field will be set.

Unfortunately, it is not linked with payroll yet. It stills creates a supplier invoice, even for an employee.

**Comment by alinepy** [comment]
Hi, I installed this module and configured the Agent to a Employe of my company, and selected de type of commision equal a Salesman, this is ok, but how I do the commision liquid to a Employee Salesman?

**Comment by max3903** [comment]
@alinepy As I said, it is not linked with payroll yet. It creates a supplier invoice for the employee.

**Comment by pedrobaeza** [comment]
Please check known issue section which explains that there's functionality missing that has to be developed: https://github.com/OCA/commission/tree/8.0/hr_commission#known-issues--roadmap
