### ISSUE TITLE
Commission for Odoo v8?

### ISSUE THREAD

**Issue by GillPotter** [OCA/commission#10]
I am interested in a module for Odoo Version 8 which I can use to allocate sales commission to agents who introduce customers. It looks like this could be the place to find it - is anyone working on it or have plans to do so in the near future?
Many thanks, Gill

**Comment by pedrobaeza** [comment]
There is already an attempt. Look at https://github.com/OCA/commission/pull/7 and put any comment there.

**Comment by manuelfcordoba** [comment]
Hello,
I have been trying the module in v8 and i cant make the settlements of these commissions.
Is it working already?

**Comment by pedrobaeza** [comment]
Yeah, of course. The settlements are made for past periods, not the current one. Put a date in the next settlement period if you want to do that.
