### ISSUE TITLE
net_amount should be like untaxed amount

### ISSUE THREAD

**Issue by scigghia** [OCA/commission#106]
I think here https://github.com/OCA/commission/blob/8.0/sale_commission/models/account_invoice.py#L150
the correct way should be like this
```
l = line.invoice_line
subtotal = l.invoice_line_tax_id.compute_all(
    (l.price_unit * (1 - (l.discount or 0.0) / 100.0)),
     l.quantity, l.product_id, line.invoice.partner_id)['total']
```
using account.tax to compute the untaxed amount.

**Comment by pedrobaeza** [comment]
Closing as there's already a PR.
