### ISSUE TITLE
Flow chart to settle and invoice commissions please?

### ISSUE THREAD

**Issue by tkontogi** [OCA/commission#112]
Hello,

sale_commission

This looks a brilliant module but not all of us can read through the code or know python.

Is there a clear step by step flow chart on how to start with an invoice, add commission agent on the line and end up paying the agent?

I have many invoices, and now that it is time to settle the payments (year closure) I get zero as settled amounts for all agents.

I tried in the lab with agent=user=supplier  or agent=user  or agent=supplier  and in all cases agent!=employee

Thank you very much.

**Comment by pedrobaeza** [comment]
See the README, try it in runbot, or ask in Odoo forum. Issues are for notifying problems with the module itself.

**Comment by tkontogi** [comment]
Thank you for your prompt reply.

Not trying to offend anyone here, but luck of detailed info in README is counted as bug. 

I do agree that this is not the place to ask for help, but it is my humble believe it is the right place to ask for enhancements (also in the documentation)

Thank you for your contribution to the community which my comments have no intention to reduce it.

**Comment by pedrobaeza** [comment]
Well, the problem is that if nobody contributes with proper documentation, the module won't have it, so it's a cycle... Anyway, sometimes people want to document all the part of Odoo that any module expands, and that's out of the scope of the module itself. Besides, I don't know which module you have problem with (as you are not indicating it).

**Comment by tkontogi** [comment]
Got so stuck on trying to figure out how to make it work, that I missed that part!!

Corrected the initial comment

The module is: sale_commission

**Comment by pedrobaeza** [comment]
The typical knowledge issue with this module is that you try to make the settlement of invoices of the current period, and for that, you need to put a date in the future when the current period is past.
