### ISSUE TITLE
Single invoice for all settlements?

### ISSUE THREAD

**Issue by tkontogi** [OCA/commission#113]
It would be really convenient to have the option to invoice all open settlements in a single invoice.

Maybe it can be done via journal entries, or it has been explained in other git reports, however I did not find it.

Apologies in advance if this is a duplicate.

**Comment by pedrobaeza** [comment]
If you are talking about all open settlements for the same agent, that's not the usual case: people wants to be paid as soon as possible. You don't join several settlements in one invoice. If that's your case, you can use the module for merging invoices.

If you're talking about all the settlements from all the agents, that's something without meaning, as each agent is a different supplier.

**Comment by tkontogi** [comment]
Thank you for being so prompt.
Indeed the request was for a single agent.
And I was not aware of the invoices merge module. Your hint was of great help.
