### ISSUE TITLE
Does this plugin work with v10?

### ISSUE THREAD

**Issue by masterseo2000** [OCA/commission#129]
Does this app work on V10 if not is there another free app that would do it?

**Comment by wetmount** [comment]
Tried it today as of 2017/9/26 and it's not working. It seems migration to v10 is not complete yet.

**Comment by JordiBForgeFlow** [comment]
You can review https://github.com/OCA/commission/pull/117

The module.is about to be.merged

**Comment by pedrobaeza** [comment]
Closing as migrated long time ago.
