### ISSUE TITLE
[commision odoo 9] error after installing module

### ISSUE THREAD

**Issue by fgarcia-humanoide** [OCA/commission#131]
After installing the module, I can't create a procuct. This error appears:

Error: Campo desconocido cost_method en el dominio ["&",["valuation","=","real_time"],["cost_method","in",["standard","average"]]]

http://192.168.17.123:8069/web/content/431-4a157d1/web.assets_backend.js:3223
Traceback:
compute_domain@http://192.168.17.123:8069/web/content/431-4a157d1/web.assets_backend.js:3223:42
compute_domain@http://192.168.17.123:8069/web/content/431-4a157d1/web.assets_backend.js:3598:339
process_modifiers@http://192.168.17.123:8069/web/content/431-4a157d1/web.assets_backend.js:3639:41
trigger@http://192.168.17.123:8069/web/content/246-167c2f0/web.assets_common.js:2614:166
trigger@http://192.168.17.123:8069/web/content/246-167c2f0/web.assets_common.js:2616:636
on_form_changed@http://192.168.17.123:8069/web/content/431-4a157d1/web.assets_backend.js:3549:68
load_record/<@http://192.168.17.123:8069/web/content/431-4a157d1/web.assets_backend.js:3546:1
then/</</<@http://192.168.17.123:8069/web/content/246-167c2f0/web.assets_common.js:650:678
fire@http://192.168.17.123:8069/web/content/246-167c2f0/web.assets_common.js:644:281
add@http://192.168.17.123:8069/web/content/246-167c2f0/web.assets_common.js:645:467
then/</<@http://192.168.17.123:8069/web/content/246-167c2f0/web.assets_common.js:650:631
each@http://192.168.17.123:8069/web/content/246-167c2f0/web.assets_common.js:473:758
then/<@http://192.168.17.123:8069/web/content/246-167c2f0/web.assets_common.js:650:553
Deferred@http://192.168.17.123:8069/web/content/246-167c2f0/web.assets_common.js:651:189
then@http://192.168.17.123:8069/web/content/246-167c2f0/web.assets_common.js:650:518
load_record@http://192.168.17.123:8069/web/content/431-4a157d1/web.assets_backend.js:3545:360
trigger@http://192.168.17.123:8069/web/content/246-167c2f0/web.assets_common.js:2614:166
trigger@http://192.168.17.123:8069/web/content/246-167c2f0/web.assets_common.js:2616:636
load_defaults/<@http://192.168.17.123:8069/web/content/431-4a157d1/web.assets_backend.js:3548:215
then/</</<@http://192.168.17.123:8069/web/content/246-167c2f0/web.assets_common.js:650:678
fire@http://192.168.17.123:8069/web/content/246-167c2f0/web.assets_common.js:644:281
fireWith@http://192.168.17.123:8069/web/content/246-167c2f0/web.assets_common.js:649:198
Deferred/</deferred[tuple[0]]@http://192.168.17.123:8069/web/content/246-167c2f0/web.assets_common.js:651:31
fire@http://192.168.17.123:8069/web/content/246-167c2f0/web.assets_common.js:644:281
fireWith@http://192.168.17.123:8069/web/content/246-167c2f0/web.assets_common.js:649:198
then/</</<@http://192.168.17.123:8069/web/content/246-167c2f0/web.assets_common.js:650:849
fire@http://192.168.17.123:8069/web/content/246-167c2f0/web.assets_common.js:644:281
fireWith@http://192.168.17.123:8069/web/content/246-167c2f0/web.assets_common.js:649:198
then/</</<@http://192.168.17.123:8069/web/content/246-167c2f0/web.assets_common.js:650:849
fire@http://192.168.17.123:8069/web/content/246-167c2f0/web.assets_common.js:644:281
fireWith@http://192.168.17.123:8069/web/content/246-167c2f0/web.assets_common.js:649:198
done@http://192.168.17.123:8069/web/content/246-167c2f0/web.assets_common.js:1040:86
callback@http://192.168.17.123:8069/web/content/246-167c2f0/web.assets_common.js:1060:15

**Comment by pedrobaeza** [comment]
This has nothing to do with this module. Check the domain and you will see that they are not fields of this module.
