### ISSUE TITLE
[sale_commission] V10 bug

### ISSUE THREAD

**Issue by lucode** [OCA/commission#134]
There is a bug in combination of the project_issue module. If I install sale_commission and then project_issue I get the following error:
```
  File "/opt/odoo/odoo-server10/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: foreign key constraint "res_partner_commission_fkey" cannot be implemented
DETAIL:  Key columns "commission" and "id" are of incompatible types: double precision and integer.
```
If I install project_issue first then it is fine.

**Comment by hurrinico** [comment]
Hi @lucode i've recently tried to reproduce the issue locally but everything looks fine. Can you check it? thank you

**Comment by lucode** [comment]
Hi @hurrinico I can't reproduce the issue my self anymore. So I close the post.
