### ISSUE TITLE
[sale_commission] V10 Creating commission invoice, get a warning "Could not find any account to create the invoice"

### ISSUE THREAD

**Issue by Plaoo** [OCA/commission#140]
Hi guys, I try sale_commission module for odoo v.10 with demo data. I can't create a Settlements with agent field, this make a problem when i try to create a commission invoice, if click on "Create Invoices" I get this warning **"Configuration error!
Could not find any account to create the invoice, are you sure you have a chart of account installed?"**
What should I set up in accounting?

**Comment by pedrobaeza** [comment]
Sorry, but this is not a bug, so you have to go to official documentation or Odoo forums to see how to properly configure Odoo accounting.
