### ISSUE TITLE
No settlement possible

### ISSUE THREAD

**Issue by damsoi01** [OCA/commission#145]
Odoo 10
Hello everyone,
I assigned agents (who are also employees as salespersons) to clients, and now it's the first month, I want to settle the commissions for each agent to know what to pay them and the menu settlement returns an empty table.
I thought I might have misconfigured the module or something, but all the sales have the agent assigned to each line of product and the total of coms appears after the total the client paid/must pay.
Anybody else with the issue?
Thanks a lot!
![01](https://user-images.githubusercontent.com/17989353/35543608-36e0bf8a-0523-11e8-87d5-f3c7e0dbde7f.png)
![02](https://user-images.githubusercontent.com/17989353/35543609-36faa9a4-0523-11e8-859a-a0bc0449ec9c.png)

**Comment by pedrobaeza** [comment]
You have to make the settlement in a date in the future that has passed the period interval. For example, for settlement of January, you have to put a date in February.

**Comment by damsoi01** [comment]
I understand, I tried it and it looks like it's working indeed!
Silly me, I was settling within the range of the settlement!

**Comment by damsoi01** [comment]
Hello,
I upgraded my platform to Odoo 11, upgraded the module as well, and it works to create settlements, only issue is with the invoicing. I get an error message.
![screen shot 2018-05-17 at 11 18 57 am](https://user-images.githubusercontent.com/17989353/40193501-af480334-59c4-11e8-8b4c-8b15294301a4.png)
![screen shot 2018-05-17 at 11 19 09 am](https://user-images.githubusercontent.com/17989353/40193504-af6dc9f2-59c4-11e8-817e-b39c0d94a4ca.png)

**Comment by damsoi01** [comment]
I put a date to try and see if it changes anything but it doesn't
