### ISSUE TITLE
commission in invoice not set

### ISSUE THREAD

**Issue by antwertinger** [OCA/commission#15]
If you switch the workflow from 
Sales Order -> Invoice 
to
Sales Order -> Delivery -> Invoice
the commission in the invoice is not set if in the sales order a commission is set.

**Comment by pedrobaeza** [comment]
You should try new version, that is on https://github.com/OCA/commission/pull/14

**Comment by ivantodorovich** [comment]
Should this be closed?

**Comment by pedrobaeza** [comment]
Yeah, that's it
