### ISSUE TITLE
Button "Recompute Line Agents" disappears!

### ISSUE THREAD

**Issue by NPubul** [OCA/commission#152]
When We send a quation via button "sen by email", the button "Recompute Line Agents" disappears!

Thanks!!

**Comment by pedrobaeza** [comment]
Version?

**Comment by NPubul** [comment]
10.0.1.0.7

Lo curioso es que luego en el borrador de la factura vuelve a aparecer

 

PRESU

 



 

BORRADOR FACTURA

 



 

 

Aprovecho para comentaros otra cosa que nos pasa; es que si en un presupuesto y pedido de venta tenemos las comisiones calculadas y si en el borrador editas para por ejemplo cambiar la fecha, te borra las comisiones y si no vas a abajo a calcularlas otra vez y validas la factura va sin camisones L

 

Gracias!

**Comment by pedrobaeza** [comment]
You have to write in English, and what you are commenting is the expected behavior. Check Known issues section in the README.
