### ISSUE TITLE
commission should be deducted from margin

### ISSUE THREAD

**Issue by ferdiga** [OCA/commission#153]
![image](https://user-images.githubusercontent.com/6248560/39089350-67975354-45c5-11e8-913b-e3c0f1535ad2.png)

**Comment by pedrobaeza** [comment]
For that, you will need to develop a bridge module `sale_commission_margin`, as it's not covered. Any way, some people will argue that the don't want to consider the commission as a margin reduction, but other kind of cost.

**Comment by pedrobaeza** [comment]
Any way, this is not a bug itself, but a missing feature/module, so I close.
