### ISSUE TITLE
[11.0][sale_commission] Cannot add lines to an invoice

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/commission#154]
Due to a bug in Odoo (see https://github.com/odoo/odoo/pull/24530) when you now create a new invoice and try to add a line you'll get the following error:

![image](https://user-images.githubusercontent.com/7683926/39528608-d740e26c-4e24-11e8-80d5-07eb7e1b5594.png)

**Comment by pedrobaeza** [comment]
Solution in #151, but for v10.

**Comment by JordiBForgeFlow** [comment]
I don't think so... The error is explained in https://github.com/odoo/odoo/pull/24530

**Comment by pedrobaeza** [comment]
OK, then it should be fixed already in latest builds.

**Comment by JordiBForgeFlow** [comment]
The PR merged by odoo does not fix the problem.

**Comment by pedrobaeza** [comment]
Well, but this shouldn't be fixed here as said in the PR, but on Odoo itself.

**Comment by pedrobaeza** [comment]
AFAIK, the error is not reproducible anymore, but please comment if so, and put all the details.
