### ISSUE TITLE
Sales Comissions - sale_commission v 10.0.1.0.7

### ISSUE THREAD

**Issue by NPubul** [OCA/commission#158]
Helo!, two things:

1.- I have set for comissions Invoice Status "Payment Based", but when we do the settlement it takes the date of the invoice instead of the date of payment.  Example.  I have an Invoice dated April27 and payd May 03 and it is en April settelmentes.

2.- When in an invoice there are two payment terms, it makes me the total settlement without having charged the second term

Thaks!!

**Comment by pedrobaeza** [comment]
For 1, that's the intended behavior. There's no problem in doing multiple settlements for the same period, and including them on payment date will cause other problems.

For 2, settlement is only done on full invoice paid also on current design.
