### ISSUE TITLE
[9.0]/[10.0][sale_commission] Error in assigning invoice date.

### ISSUE THREAD

**Issue by pedroortega-punt** [OCA/commission#165]
Hello,

Error in invoices to calculate the commission in invoice lines, when an invoice is created and lines are added, register the agent assigned to the client in the lines.

Once the invoice is saved without assigning an invoice date, and then we want to assign a date to the invoice, recalculate the records of the lines and show as if there were two records in the agents, and when we save it indicates "missing record" error.

We have made checks in programming to solve the problem and after several hours and crawling in the methods, we could not detect the error. We think that the problem may be with the widget, but we have not solved it either.

This error is in verified V9 runbot.

In runbot v10 we have made the checks and the error of two records in agents no longer appears, but at the time of assigning date in the invoice, instead of assigning two records in the agents, it eliminates it and remains as 0 records.

**Comment by pedrobaeza** [comment]
This is a problem in the web client itself with nested one2many fields. I have workarounded this in v10 with #151 (check known issues for its limitations). Something similar can be done on v9.

**Comment by pedrobaeza** [comment]
Closing as answered and it's working properly right now.
