### ISSUE TITLE
Error with installation of Module sale_commission v11.0

### ISSUE THREAD

**Issue by datahaulic** [OCA/commission#167]
My attempted installation of sales_commissions module via odoo.sh v11 is failing and returning the follow error: **raise UserError(_('Please define an accounting sales journal for this company.'))**

Any help and guidance on this greatly appreciated.

**Comment by pedrobaeza** [comment]
Sorry, but the error is clear and this has nothing to do with the module itself. Install a chart of accounts in your company to have a sales journal.

**Comment by datahaulic** [comment]
Thank you for your response @pedrobaeza I have setup the sales journal but still encountering the error. Is there a specific configuration that's required for the sales journal?

**Comment by pedrobaeza** [comment]
Not AFAIK. Try on a fresh database. You can see on runbot + Travis that is being installed without problems.

**Comment by datahaulic** [comment]
I tested on runbot and saw it working there. Tried on a fresh Enterprise .sh database but still encountering errors. Nothing seems immediate between setting in runbot vs. my environment apart from the enterprise versions.

**Comment by datahaulic** [comment]
I still was not able to get by the error as constantly trying. Are there any other possible recommendations/suggestions in getting a resolution?

**Comment by datahaulic** [comment]
Odoo support came back saying all is well as far as the setup and configuration goes and suggested I check again with OCA seeing that the errors are generated during the series of test. I am attaching a txt file which contains messages from the error log. Can you take a look at this please?
[Odoo_Sales_Commission_Error.txt](https://github.com/OCA/commission/files/2177599/Odoo_Sales_Commission_Error.txt)
