### ISSUE TITLE
Can't Install Module on Odoo 11

### ISSUE THREAD

**Issue by ruthbeat** [OCA/commission#173]
Error while importing module 'sale_commission':
 "Fallo en la carga del módulo sale_commission: no se pudo procesar el archivo /tmp/tmpjquc5nq3/sale_commission/security/ir.model.access.csv:
 
No se han encontrado registros coincidentes para id. externo 'model_sale_commission' en el campo 'Object'
Missing required value for the field 'Object' (model_id)

No se han encontrado registros coincidentes para id. externo 'model_sale_commission' en el campo 'Object'
Missing required value for the field 'Object' (model_id)

No se han encontrado registros coincidentes para id. externo 'model_sale_commission' en el campo 'Object'
Missing required value for the field 'Object' (model_id)

No se han encontrado registros coincidentes para id. externo 'model_sale_commission_section' en el campo 'Object'
Missing required value for the field 'Object' (model_id)

No se han encontrado registros coincidentes para id. externo 'model_sale_commission_section' en el campo 'Object'
Missing required value for the field 'Object' (model_id)

No se han encontrado registros coincidentes para id. externo 'model_sale_order_line_agent' en el campo 'Object'
Missing required value for the field 'Object' (model_id)

No se han encontrado registros coincidentes para id. externo 'model_account_invoice_line_agent' en el campo 'Object'
Missing required value for the field 'Object' (model_id)

No se han encontrado registros coincidentes para id. externo 'model_account_invoice_line_agent' en el campo 'Object'
Missing required value for the field 'Object' (model_id)

No se han encontrado registros coincidentes para id. externo 'model_sale_commission_settlement' en el campo 'Object'
Missing required value for the field 'Object' (model_id)

No se han encontrado registros coincidentes para id. externo 'model_sale_commission_settlement' en el campo 'Object'
Missing required value for the field 'Object' (model_id)

No se han encontrado registros coincidentes para id. externo 'model_sale_commission_settlement' en el campo 'Object'
Missing required value for the field 'Object' (model_id)

No se han encontrado registros coincidentes para id. externo 'model_sale_commission_settlement_line' en el campo 'Object'
Missing required value for the field 'Object' (model_id)

No se han encontrado registros coincidentes para id. externo 'model_sale_commission_settlement_line' en el campo 'Object'
Missing required value for the field 'Object' (model_id)

No se han encontrado registros coincidentes para id. externo 'model_sale_commission_settlement_line' en el campo 'Object'
Missing required value for the field 'Object' (model_id)"

**Comment by pedrobaeza** [comment]
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (http://runbot.odoo-community.org), so please be sure you are following the proper installation instructions for Odoo itself.

**Comment by ruthbeat** [comment]
Odoo 11 Comunity sobre debian instalacion limpia sin datos de ejemplo base de datos creada en español

**Comment by ruthbeat** [comment]
@pedrobaeza ?

**Comment by pedrobaeza** [comment]
Nothing more to say. You should deal with the problem, as it's not something of the module.
