### ISSUE TITLE
[ERROR] [11.0] Settlement Invoices don't compute taxes

### ISSUE THREAD

**Issue by angelmoya** [OCA/commission#186]
If commission product has taxs, when you create invoice from settlemente taxes are not computed.

Tested on runbot.

![vendor bill odoo](https://user-images.githubusercontent.com/6750341/47987654-58af9c00-e0e0-11e8-8e0e-9db1ae50f566.png)

We will fix it on version 11.0

**Comment by angelmoya** [comment]
Fixed on #187

**Comment by bodedra** [comment]
These issue can be close as a fixed reference https://github.com/OCA/commission/pull/187
