### ISSUE TITLE
[11.0][Bug] Issue on commission analysis: Can not open it

### ISSUE THREAD

**Issue by ghost** [OCA/commission#194]
Hi guys,

I got this error when trying to open menu Invoicing > Reporting > Management > Commission Analysis.
![screenshot from 2018-12-20 15-13-45](https://user-images.githubusercontent.com/10511982/50273834-51650780-046e-11e9-890d-933ffa3687ee.png)

Field `amount` is defined in Abstract model `sale.commission.line.mixin` but it is not re-defined the logic by inherited models `account.invoice.line.agent` and it causes the problem.

**Comment by ghost** [comment]
reproduced at runbot http://3350927-11-0-9f64c4.runbot1.odoo-community.org/web?debug=1#view_type=list&model=account.invoice&menu_id=136&action=217

**Comment by pedrobaeza** [comment]
It's not by the reason you stated, but there's obviously a problem. Solved in the above commit.

**Comment by ghost** [comment]
Thanks for your help @pedrobaeza
