### ISSUE TITLE
Multiple agents on same invoice line

### ISSUE THREAD

**Issue by pedrocs-exo** [OCA/commission#195]
Hi,

I hit an error when I try to save an invoice containing 2 agents on the same line. Is it a bug or is the code designed to handle 1 agent per line?

I'm on v10. The offending code is the `self.ensure_one()` on the _compute_amount() method. If it's just a bug, I can help squash it.

Thx!

**Comment by pedrobaeza** [comment]
Please update to latest code, where there is no such problem.

**Comment by pedrocs-exo** [comment]
Thanks Pedro,

I'm using the latest code. The steps to reproduce the error are quite simple:

1. Create two different agents and configure their commissions
2. Create a sales order and add a line to it. Add the two agents to the line
3. Save and the error occurs

The traceback is:
```
(...)
  File "/odoo/odoo/odoo/fields.py", line 981, in compute_value
    self._compute_value(records)
  File "/odoo/odoo/odoo/fields.py", line 972, in _compute_value
    getattr(records, self.compute)()
  File "/odoo/oca/symlinks/sale_commission/models/sale_order.py", line 74, in _compute_amount
    line.object_id.product_uom_qty)
  File "/odoo/oca/symlinks/sale_commission/models/sale_commission_mixin.py", line 139, in _get_commission_amount
    self.ensure_one()
  File "/odoo/odoo/odoo/models.py", line 4848, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: sale.order.line.agent(33, 34)
```

**Comment by pedrobaeza** [comment]
OK, seen the error and fixed in 82ccffe5a1e8a2da4123a53a391037b0d069c011

Thanks for reporting.

**Comment by pedrocs-exo** [comment]
Thank you!

**Comment by pedrocs-exo** [comment]
Just wanted to let you know that the problem only occurs on sales orders. Invoice lines with multiple agents work fine.

**Comment by pedrobaeza** [comment]
Fixed in https://github.com/OCA/commission/commit/3894626510162410e6c378058f69351f07c33325
