### ISSUE TITLE
I can't make settlements

### ISSUE THREAD

**Issue by ghost** [OCA/commission#20]
I am in the group Sales Manager. When I try to make new Settlements, and I have done some sales orders, I find this warning:

![image](https://cloud.githubusercontent.com/assets/8233008/7796259/b7f6b494-02dd-11e5-8b29-93bcf7285062.png)

I think Group Sales Manager must have all Access Rights to the object sale.commission.settlement.line.

**Comment by pedrobaeza** [comment]
I have fixed it via direct commit because it's a blocking issue in https://github.com/OCA/commission/commit/c4d756896b2f05bd2b8684941ee3e42b8902f51d
