### ISSUE TITLE
Problema al generar factura de comisión

### ISSUE THREAD

**Issue by marionumza** [OCA/commission#210]
Hola que tal, tengo un problema al generar la factura de comisión, cuando presiono el botón de crear facturas me sale el siguiente cartel

No puede completarse la operación, probablemente debido a lo siguiente:
- eliminación: es posible que esté intentando eliminar un registro mientras que otros registros todavía tienen referencias a él
- creación/actualización: un campo obligatorio no se ha introducido correctamente

[objeto con referencia: currency_id - currency.id]

En la parte de "Pago de factura de comisiones" me pasa lo mismo, lo he probado con datos demo y con base en blando, y activando y desactivando el multimoneda, también he buscado este issue en este repositorio y no lo he encontrado por eso lo estoy publicando. Saludos

**Comment by marionumza** [comment]
Estoy trabajando con la version 11 de Odoo CE

**Comment by sebaramis** [comment]
Replique el fallo y me pasa lo mismo, a la espera de solución.

**Comment by pedrobaeza** [comment]
Please, always in English, and indicating Odoo version and detailed steps to reproduce the problem.
