### ISSUE TITLE
[11.0] Problem generating commission invoice

### ISSUE THREAD

**Issue by marionumza** [OCA/commission#211]
Hello, I have a problem when generating the commission invoice, when I press the button to create invoices I get the following poster:
The operation can not be completed, probably due to the following:

deletion: you may be trying to delete a record while other records still have references to it
creation / update: a mandatory field has not been entered correctly
[object with reference: currency_id - currency.id]

In the part of "Commission bill payment" the same thing happens to me, I have tested it with demo data and based on blank, and activating and deactivating the multi-currency, I have also searched this issue in this repository and I have not found it for that reason I'm publishing it. regards

**Comment by pedrobaeza** [comment]
Please try to reproduce the problem in runbot. Do you have latest code version?

**Comment by marionumza** [comment]
I have the latest version of the code that I downloaded when generating this issue.
I have already tried the module installing Odoo 11 CE from github, also downloading the windows installer package and also with docker, I tried it creating a base with demo data and another base without data.
Please, send me a link to try in rumbot an instance with the module sale_commission to do the test there too. Thank you

**Comment by pedrobaeza** [comment]
You have it on the README, but I paste it here:

https://runbot.odoo-community.org/runbot/165/11.0

**Comment by marionumza** [comment]
I already try rumbot and there it does not happen to me

**Comment by pedrobaeza** [comment]
Then it's something on your deployment, as already stated. You have to properly configure everything, and avoid third party modules that can waste this.

**Comment by marionumza** [comment]
I did more tests and note that when installing the Argentine location of IngAdhoc the module behaves in the way I mentioned before, it is a pity that it does not work well in this location, since the location that is predetermined in Odoo does not work in Argentina for the eletronic bills

**Comment by pedrobaeza** [comment]
Then seems a problem with that one. You should contact Ing. Adhoc to tell about this. They are very nice and at least give you some pointers.
