### ISSUE TITLE
[10.0][sale_commission]. When changing warhouse or analytic account, agemts are deleted

### ISSUE THREAD

**Issue by javierjcf** [OCA/commission#212]
Hi,
To reproduce this issue:

- Create a new Order

- Create a new sale order line set one agent with his commission, save and close the line.

- WHITHOUT SAVING THE ORDER, change the warehouse field to another value.

If you return to the sale order line you will see the record is there but agent and commission is missing.

I think is something about the update of a field in an onchange and the memory vals being prepared to being saved.

**Comment by pedrobaeza** [comment]
Yes, this is a known issue of the ORM in this version:

https://github.com/OCA/commission/tree/10.0/sale_commission#known-issues--roadmap
