### ISSUE TITLE
Sale commission invoices to providers

### ISSUE THREAD

**Issue by estekadigital** [OCA/commission#220]
I'd like to know if I can use this module or I should adapt a new one for the case I will desribe below. At least, I think this module is a nice start point for my requirements. Of course, if I finally have to deploy it as a new module I'd like to add it to the repo if it is of any intestest.

The scenario is as follows:

Besides the normal purchase-sale-invoce workflow, the company A has some customers who purchase products through them but it is "Provider X" who attends the order, they receive the sale order through Company A, and Provider X sends the items and invoices the final customer of Company A. Company A wants to keep track of the items purchased and monthly invoice to Provider X for the commission on the purchases, the lines of that invoice should contain the related order and commissions of that period, not the purchased items.

Can I use this module for that purpose or should I create a new one?

**Comment by pedrobaeza** [comment]
This module doesn't cover this and the main problem you will have is to track that a received product from a determined supplier is the one that has been shipped for a customer. This can only be done through products with lots.

**Comment by estekadigital** [comment]
By now let's skip the trazability of the product (I think this could be covered by using the dropshipping module right?), I just need to keep record of the sale orders and instead of invoicing the final customer, invoice the provider with the monthly % sales commission (commission rates should be based/configured on product - customer - provider). Thanks for your help

**Comment by pedrobaeza** [comment]
Then just add them as agents and define the commission.

**Comment by estekadigital** [comment]
Hi @pedrobaeza , thanks for your help, but I still got one doubt. Isn't an agent thought to be paid instead of to be billed ?

**Comment by pedrobaeza** [comment]
Right, I didn't get that part. Then you only need to add a check on the agent for specifying that there should be customer invoices, and when invoicing, if the check is marked, then switch type and journal of the invoice.
