### ISSUE TITLE
[12.0] Error line 67, in _compute_commission_status

### ISSUE THREAD

**Issue by ilaria-franchini** [OCA/commission#222]
line.commission_status = _( "%s commission agents" ) % len(line.agents)

When I add a line with more of an agent to an invoice, an error occurs to line 67 in _compute_commission_status of sale_commission_mixin.py

**Comment by pedrobaeza** [comment]
Which error? Is due to the translation?

**Comment by pedrobaeza** [comment]
Closing as no answer.
