### ISSUE TITLE
[12.0.2.0.0][IMP] sale_commission

### ISSUE THREAD

**Issue by max3903** [OCA/commission#226]
# sale.commission

- [ ] Add an option to type: "Flat Rate" (flat_rate)
- [ ] Add a float field "Flat Rate" (flat_rate). Show it and make it required only if the type is flat_rate.
- [ ] Add a selection field "Using" (scope) with the default option "the agent field on the partner" (res_partner_agent)

# sale.commission.line

- [ ] Edit the get_commission_amount method to support flat rate

# sale.commission.make.settle

- [ ] Add a method run_cron_make_settle to:
* execute the settlements for all agents based on their period
* create the invoices from those settlements

# ir.cron

- [ ] Add a scheduled action to call run_cron_make_settle every day

# Migration

Not sure a migration script is required.

**Comment by pedrobaeza** [comment]
Seems good for me!

**Comment by pedrobaeza** [comment]
Closing as no more feedback. I have added to roadmap for not losing the tracking: 021f219fd4d6f31fc20c7f7885be00dd31ed21b5
