### ISSUE TITLE
[ADD] sale_commission_fieldservice

### ISSUE THREAD

**Issue by max3903** [OCA/commission#227]
This module allows you to use Field Service locations to compute commissions.

It adds a new option to scope: Using the related owner of FSM locations, so you can define a commission like 
* Give a 2% commission to the owner of a location based on the revenue generated by that location

# Technical Specifications

## sale.commission

- [ ] Add an option to scope: "the related owner of FSM locations" (fsm_location_owner)

## sale.commission.line

- [ ] Extend get_commission_amount method to support the new scope

**Comment by pedrobaeza** [comment]
Should this be here or in OCA/field-service?

**Comment by max3903** [comment]
Aha :) We had the same discussion with brand so I applied the same solution.

**Comment by pedrobaeza** [comment]
Hehe, ok. There's no good solution when 2 "verticals" are integrated.

**Comment by pedrobaeza** [comment]
Closing as no more discussion.
