### ISSUE TITLE
[ADD] sale_commission_agreement

### ISSUE THREAD

**Issue by max3903** [OCA/commission#228]
This module allows you to use agreements information to define and compute commissions.

It adds a new option to type: number of agreements/contracts, so you can define a commission like:
* Give a 50$ commission to the agent for each active agreements/contracts of their customers

# Technical Specifications

## sale.commission
- [ ] Add an option to amount_base_type: "Number of contracts"

## sale.commission.line

- [ ] Extend get_commission_amount method to support the new base

**Comment by pedrobaeza** [comment]
The problem I see is to now, all settlement lines are linked to an invoice line. With this, we will have other without that link, that can cause side effects of code is expecting to have that link.

**Comment by max3903** [comment]
@pedrobaeza The related invoice line is the one that pays the commission. This will still be the case.

**Comment by pedrobaeza** [comment]
Sorry, I mean the invoice line agent: https://github.com/OCA/commission/blob/e41de24dd66f35a80fcde3845cd02758ed22a886/sale_commission/models/settlement.py#L157

**Comment by max3903** [comment]
@pedrobaeza So what do you suggest?

**Comment by pedrobaeza** [comment]
What about?:

- Abstract settlement lines for not depending on invoice agent line (which is required right now).
- Get data (agent, amount, etc) through computed fields that are overwritten depending on your case.

**Comment by pedrobaeza** [comment]
Closing as no more answers.
