### ISSUE TITLE
[12.0] sale_commission_pricelist: Does not work on change product

### ISSUE THREAD

**Issue by FFernandez-PlanetaTIC** [OCA/commission#230]
**Impacted versions:**

At least 12.0

**Steps to reproduce:**

Set up a commission for a product in a pricelist and optionally a discount:

![image](https://user-images.githubusercontent.com/39995504/70985700-d522f580-20bc-11ea-8dea-42d34e53ebbf.png)

**Current behavior:**

On select the product in a sale the discount is set correctly:

![image](https://user-images.githubusercontent.com/39995504/70985906-38148c80-20bd-11ea-9bca-fad43b05157d.png)

But not the commission:

![image](https://user-images.githubusercontent.com/39995504/70985920-3f3b9a80-20bd-11ea-9ee9-e0fddfb71375.png)

Expected behavior:

The commission should be "3% [FURN_6666] ..." and the button "Recompute lines agents" fix it.

**Comment by FFernandez-PlanetaTIC** [comment]
Hi,

Method __onchange_product_id_sale_commission_pricelist_ sets the commission properly but it is not updated in the web client:

https://github.com/OCA/commission/blob/12.0/sale_commission_pricelist/models/sale_order.py#L29

Thanks!

**Comment by pedrobaeza** [comment]
Have you tried this on runbot? This is working for one of our customer that is using it in v12

**Comment by FFernandez-PlanetaTIC** [comment]
Yes, screenshots are from runbot and my test is still there:

http://3401350-12-0-b53ff9.runbot1-2.odoo-community.org

**Comment by pedrobaeza** [comment]
Try to use the other option of not showing the discount to see if that's the problem

**Comment by FFernandez-PlanetaTIC** [comment]
It still doesn't work without showing the discount or without discount.

I debugged the onchange method and it assigns the desired commission:

https://github.com/OCA/commission/blob/12.0/sale_commission_pricelist/models/sale_order.py#L29

But the change does not reach to the web client...

**Comment by pedrobaeza** [comment]
Maybe a question of readonly in the corresponding field?

**Comment by FFernandez-PlanetaTIC** [comment]
I don't think so, the agents field is not read-only, neither in the view nor in the model.

Using browser developer tools I see that in the response to the onchange request there is no change in agents and commissions...
