### ISSUE TITLE
[10] Issue with sale_commission and partner_multi_company

### ISSUE THREAD

**Issue by igallart** [OCA/commission#233]
Hello, when you have module partner_multi_company and sale_commission installed, if you update sale_commission, when is executed the script migrate:

> def migrate(cr, installed_version):
    """Populate company field for settlements"""
    # Populate company_id for sale.commission.settlement,
    # get the company from the settlement's agent's company
    cr.execute(
        'UPDATE sale_commission_settlement '
        'SET company_id = res_partner.company_id '
        'FROM res_partner '
        'WHERE sale_commission_settlement.agent = res_partner.id')

it fail because field company_id of res_partner is empty.

**Comment by rousseldenis** [comment]
Indeed, company_id can be void.

@SimoRubi Could you check at this ?

**Comment by SimoRubi** [comment]
yep, I'll look into it when I have some spare time, thanks

**Comment by pedrobaeza** [comment]
Any news about this?

**Comment by SimoRubi** [comment]
Hi, I still haven't looked into this: it still is in my TODO list but has very low priority so other work tasks (for our customers) usually take precedence.

**Comment by pedrobaeza** [comment]
As the version is old and is not with the main module alone, but with other combination, I'm triaging this. If the issuer has the solution, he can put a PR if he wants to fix it.

**Comment by SimoRubi** [comment]
![image](https://user-images.githubusercontent.com/32064796/86586833-d8160280-bf88-11ea-9338-d6b55cc5322a.png)
