### ISSUE TITLE
Job offer: commission module custom development

### ISSUE THREAD

**Issue by t-np** [OCA/commission#234]
i need development for a odoo v13 commission module "similar" to the oca commission but with a few more twists and bobs. General enhancements could be backported into this commission module if it fits as a base for our requirements. It is an advanced requirement where existing funcionality from another system has to be transferred into odoo.

If anyone has experience in this area and is interested, please contact me  [nihad.perva@tisso.de](mailto:nihad.perva@tisso.de?subject=[GitHub]%20commission%20module%20custom%20development)

**Comment by pedrobaeza** [comment]
Closing this as it had enough exposure.
