### ISSUE TITLE
Purchase Commission

### ISSUE THREAD

**Issue by mileo** [OCA/commission#238]
Some products are complex to buy.

For example, in the fruit and vegetable segment, the products are standardized and can be purchased from several suppliers. In this case, the buyers are also external agents.

We are looking at the feasibility of adapting the commission core to become versatile for controlling purchase and sales commissions.

cc: @CCruzArthur @bielmorales

**Comment by pedrobaeza** [comment]
It can be feasible to create a base module `commission` for defining agents and commissions and handle then at account level, perform settlements, etc, and then `sale_commission` and `purchase_commission` will manage its part. This can be done for v14 (as v13 is almost migrated in #237), and for <v14 you can depend on `sale_commission`, without being the ideal one.

**Comment by pedrobaeza** [comment]
For which version do you plan to do this?

**Comment by mileo** [comment]
The customer (@CCruzArthur @bielmorales) uses v11

**Comment by mileo** [comment]
I'll show them the modules next week and give you feedback here.

**Comment by pedrobaeza** [comment]
OK, then the only option is the second. I was about to say that if for v13, we can make the effort of bringing already `base_commission` there, but for v11 is not a possibility.

**Comment by JordiBForgeFlow** [comment]
FYI, @AaronHForgeFlow is also working on designing Supplier Rebates, using a similar mechanism as the commission, although it's a bit different concept.https://en.wikipedia.org/wiki/Rebate_(marketing)

**Comment by pedrobaeza** [comment]
@JordiBForgeFlow is that what is called "Rappel"?

**Comment by AaronHForgeFlow** [comment]
@pedrobaeza Yes, I think it is the same concept.

A company pay a higher price (full price) to the supplier. Depending on sales volumes for the products bought to that supplier, the supplier will pay back some money to the company. Basically, in this case, the commission agent will have to pay, not the company.

**Comment by pedrobaeza** [comment]
OK, thanks for the answer. @carlosdauden @sergio-teruel FYI

**Comment by sergio-teruel** [comment]
Coming soon we will carry out the PR of rappel management

**Comment by sergio-teruel** [comment]
We are working in this PR.. https://github.com/OCA/contract/pull/510

**Comment by AaronHForgeFlow** [comment]
I was also working on the same concept (https://github.com/OCA/commission/pull/239) but without involving agreements in this case.

**Comment by pedrobaeza** [comment]
Closing this as discussed.
