### ISSUE TITLE
How to run settlement

### ISSUE THREAD

**Issue by mfzoutsource** [OCA/commission#24]
Hi everyone,

I just found and tested this module. I know this module still in development but I just lost the flow. 
How do I run commission settlement after I have done register payment for that invoice.
In that invoice line "Agent and commissions"s column, it shows there is a record.
Then how do I want to process payment for that agent?

Sorry for my english. Thank you.  :)

**Comment by pedrobaeza** [comment]
The module is not in development anymore. You just need to run Sales > Configuration > Commissions > Create commission invoices

**Comment by mfzoutsource** [comment]
Oh, I'm sorry for my words. Just clear my way here.

![no record](https://cloud.githubusercontent.com/assets/13113545/8426297/4cac45a2-1f41-11e5-82fe-3d42380f09db.png)

![paid](https://cloud.githubusercontent.com/assets/13113545/8426309/6340dce2-1f41-11e5-94d5-daaae78f7a21.png)

![record](https://cloud.githubusercontent.com/assets/13113545/8426314/69d69786-1f41-11e5-93fe-d672b617d786.png)

![bank_entry_paid](https://cloud.githubusercontent.com/assets/13113545/8426330/88b8dcd6-1f41-11e5-9210-b556c155ffd1.png)

**Comment by mfzoutsource** [comment]
![creat_comm](https://cloud.githubusercontent.com/assets/13113545/8426379/df8a6f16-1f41-11e5-950f-d07b9c08a480.png)

![add_sttlement](https://cloud.githubusercontent.com/assets/13113545/8426387/e69914c4-1f41-11e5-9b7e-8c709ffa340b.png)

**Comment by pedrobaeza** [comment]
You have to made the settlements first, but settlements are not made if the period selected is not due (if you put monthly, it's not settled until next month).

**Comment by mfzoutsource** [comment]
So I just need to wait next month to look the result?
I'll try modify the code to make it show the result by today. I'm curious. :)

Thanks for helping me out @pedrobaeza

**Comment by pedrobaeza** [comment]
Yes, it's the normal flow (not testing flow), but you can test it making an invoice with commission of a past month.
