### ISSUE TITLE
Multi Currency support

### ISSUE THREAD

**Issue by Lee8009** [OCA/commission#240]
For installations using multicurrency setups, the commissions on the invoice are created / shown with the correct invoice currency. However when creating the settlements the commissions are shown in the base currency with no conversions.

i.e for a system where the base currency is in USD and an invoice is created in EUR the comm shows correctly on the invoice with the EUR currency, however when creating the settlement the settlement amount is shown in USD with the EUR value, this in turn is then carried through to the create invoice function for the agent. 

Would it not be a feature to integrate a conversion based on the Agents currency when creating settlements.

**Comment by pedrobaeza** [comment]
Yes, this is a limitation that is not taken into account for now. On 08c6004 I have added that ROADMAP on the README. You can do a PR for adding that support if you prefer.
