### ISSUE TITLE
[12.0] Commission wrong compute

### ISSUE THREAD

**Issue by josepmy** [OCA/commission#241]
Hi,
I'm using the commission module and I detected that sometimes the commission compute is wrong. Attach capture to show it. One line is correct but not the other line. In this case, the commission should be 0,10% of the total.

I have the commission assigned to the salesman and assigned to the partner.
No differences between products that work and the other one that doesn't.
I'm using customer pricelist but the commission is for all products, no matter in which pricelist they are, so I don't use the commission module pricelist nor formulas.

I read the issues but I don't found any related so I ask here about if is a bug or not.

Thanks in advance.
Salut,
Josep M

![Captura de pantalla 2020-06-01 10 13 02](https://user-images.githubusercontent.com/6210262/83397426-e5762500-a3fd-11ea-8a1a-43f01d2545cb.png)

**Comment by pedrobaeza** [comment]
Sorry, but the information provided is not enough and the screenshot say nothing. You have to provide steps to reproduce the problem in a standard runbot.

**Comment by josepmy** [comment]
OK. Going to test on runbot and report you

**Comment by pedrobaeza** [comment]
Closing as no more answer.
