### ISSUE TITLE
Installing the module “sale_commions”  error  No module named 'odoo.addons,sale_commisn'

### ISSUE THREAD

**Issue by LcL54264** [OCA/commission#244]
![image](https://user-images.githubusercontent.com/62918960/84739094-96bfb200-afdd-11ea-850d-d478f94c84f9.png)
![image](https://user-images.githubusercontent.com/62918960/84739103-99baa280-afdd-11ea-9e02-6a110c3f74b4.png)
![image](https://user-images.githubusercontent.com/62918960/84739110-9b846600-afdd-11ea-8205-279a72556d4b.png)

**Comment by pedrobaeza** [comment]
You have an altered version of the module, as no `pyoe` folder is on the official one.

**Comment by LcL54264** [comment]
> 您的模块版本已更改，因为`pyoe`官方文件夹中没有文件夹。

Then what should I do

**Comment by pedrobaeza** [comment]
Take the proper version from this repository.

**Comment by LcL54264** [comment]
> 从此存储库中获取正确的版本。

My version of Odoo is 12.0 ，Which version should I choose?

**Comment by pedrobaeza** [comment]
https://github.com/OCA/commission/tree/12.0/sale_commission

**Comment by LcL54264** [comment]
> https://github.com/OCA/commission/tree/12.0/sale_commission


Thank you very much inde

**Comment by LcL54264** [comment]
> https://github.com/OCA/commission/tree/12.0/sale_commission

This module is given by the customer. He has modified part of the encrypted code to PYOE, which needs to be supported by Python version 3.5. How can odoo modify Python version？

**Comment by pedrobaeza** [comment]
Sorry, but you are on your own with custom modifications.

**Comment by LcL54264** [comment]
> custom



> Sorry, but you are on your own with custom modifications.
So I don't know what to do
