### ISSUE TITLE
Multi-lines commissions

### ISSUE THREAD

**Issue by max3903** [OCA/commission#26]
This is to inform that we are working on improving the sale_commission module to allow to define multiple commissions on one agent.

For example, an agent can get 5% commission on his sales (his customers) in addition to 1% on the whole company sales.

The result should look like this:
![agents - odoo 2015-07-16 14-07-14](https://cloud.githubusercontent.com/assets/939952/9229684/61af8d98-40ec-11e5-81c5-a1f7cabb8a45.png)

**Comment by pedrobaeza** [comment]
Thanks for the improvement. Do you plan to add it to the main module or make it a separate one? I think the first option makes more sense

**Comment by max3903** [comment]
We plan on adding it in the main module.

**Comment by pedrobaeza** [comment]
Cool, I'll review it when done

**Comment by max3903** [comment]
#27

**Comment by pedrobaeza** [comment]
Closing as PR was proposed in #38 and finally abandoned.
