### ISSUE TITLE
[13.0] Sale commission issue with qty_invoiced

### ISSUE THREAD

**Issue by sergioeix** [OCA/commission#264]
[13.0] Community ubuntu 18
Fully reproducible on runbot
Steps to reproduce:
Set commission, agent, fixed pricelist commission and make sale order with comisionist, do delivery and crete invoice but dont confirm or post this invoice just delete draft invoice when you back to sale order qty_invoiced on sale order is not reset so you are not able to invoice it again.
Expected flow: qty_invoice is reset and the order could be invoiced again
This is exactly the flow i followed but it happens with any line with commissionist.
B/R

**Comment by pedrobaeza** [comment]
sale_commission has nothing to do with `qty_invoiced`, so I don't think the problem is due to this module.

**Comment by sergioeix** [comment]
hi @pedrobaeza i can do this flow and reproduce it on runbot.

**Comment by pedrobaeza** [comment]
Yeah, but that doesn't mean that is due to this module. If you uninstall it, does it still happen?

**Comment by sergioeix** [comment]
without this module it not happens, i test it so hard before post the issue. With this modules installed only happens with lines that have commisionist set.

**Comment by pedrobaeza** [comment]
OK, very weird, but I will investigate it.

**Comment by sergioeix** [comment]
ty sir

**Comment by sergioeix** [comment]
hello @pedrobaeza did you could reproduce this issue ?

**Comment by pedrobaeza** [comment]
Yes, but not able to find why.

**Comment by sergioeix** [comment]
Hope it could be fixed, its really anoying because it happens very often to make a mistake and have to delete draft invoices, it very anoying try to fixt it on the back end. (even changing invoice status, qty_invoiced cant be changed or at least i dont know how)

**Comment by pedrobaeza** [comment]
As info, this wasn't happening with latest code, and it was due to an ORM glitch it seems.
