### ISSUE TITLE
[13.0] sale_commission breaks on update

### ISSUE THREAD

**Issue by dennybiasiolli** [OCA/commission#268]
@pedrobaeza after the previous merge, `sale_commission` module keeps breaking during update.
 The error is `odoo.tools.convert.ParseError: "Element '<filter name="supplier">' cannot be located in parent view`, even if now the code in the template is
```
    <record id="res_partner_view_search" model="ir.ui.view">
        <field name="name">res.partner.select</field>
        <field name="model">res.partner</field>
        <field name="inherit_id" ref="account.res_partner_view_search"/>
        <field name="arch" type="xml">
            <xpath expr="//filter[@name='supplier']" position="after">
                <filter string="Agents" name="agent" domain="[('agent', '=', 1)]" help="Agent Partners"/>
            </xpath>
        </field>
    </record>
```

Any idea?

**Comment by dennybiasiolli** [comment]
It could be the renaming of the record id from `view_res_partner_filter` to `res_partner_view_search`?

**Comment by pedrobaeza** [comment]
I think it could be the removal order. Try to remove manually the previous view and then update.

**Comment by dennybiasiolli** [comment]
Yes, manually removing the previous view the update works fine, but how can I automate everything for the update in production? I'd like to avoid the manual removal of the view for every database

**Comment by pedrobaeza** [comment]
Add a migration script that removes on pre-migration such view. I can do it if you don't know how.
