### ISSUE TITLE
[13.0] sale_commission: Doesn't calculate  amount_untaxed and amount_total into invoice when use multicompany

### ISSUE THREAD

**Issue by h3nrygr** [OCA/commission#275]
Hello, 

i detected this issue.

[13.0] Community and Enterprise ubuntu 18

Steps to reproduce:
- multi companies and currencies
- create two or more companies with their respective currencies
- make the commission, agent and commission type settings;
- create a new sales invoice
- change the currency to a different one from your country
- add lines to the invoice

You will notice that the variables **amount_untaxed** and **amount_total** are not being calculated.

![problema_commisson](https://user-images.githubusercontent.com/453923/104084753-e2ef6f80-5217-11eb-815e-60551e744c00.png)

Thanks.

**Comment by pedrobaeza** [comment]
Please try in a runbot without account_global_discount module.

**Comment by h3nrygr** [comment]
The problem persists.
![problema_2](https://user-images.githubusercontent.com/453923/104151241-7e184e80-53aa-11eb-84b5-a62b5848fe49.png)


The problem is caused by the rewriting of the **attrs** parameter in the **account.account_move_views.xml** view
![parte1](https://user-images.githubusercontent.com/453923/104151083-0813e780-53aa-11eb-9118-4ea1b281b710.png)

It is rewritten by:

sale_commission.account_move_views.xml
![parte2](https://user-images.githubusercontent.com/453923/104151107-19f58a80-53aa-11eb-8d5c-2d0d764c0fa8.png)

**Comment by pedrobaeza** [comment]
As reference, this was fixed in #282
