### ISSUE TITLE
[14.0] _prepare_invoice_line() got an unexpected keyword argument 'sequence'

### ISSUE THREAD

**Issue by maherkhalil07** [OCA/commission#291]
in odoo v 14 community edition, I get the bellow mentioned error while converting sale order to invoice
_prepare_invoice_line() got an unexpected keyword argument 'sequence'
attached photo for the error
![Screenshot 2021-02-28 01:17:54](https://user-images.githubusercontent.com/38738435/109402964-df987a80-7962-11eb-928d-74ca810049b6.png)

**Comment by pedrobaeza** [comment]
The module is not yet migrated to v14 in the OCA branch, so this report doesn't qualify as issue, so closing.
