### ISSUE TITLE
write error when using the comission module with standard Odoo rental module

### ISSUE THREAD

**Issue by isofterp** [OCA/commission#295]
module: sale_commission
version: 13.0

**Steps to reproduce**
- ...
Install sales, commission and rental module (sale_renting).  
**Current behavior**
Create new sales order, choose a product, add commission line. Upon choosing Save button, the following error is produced.

Traceback (most recent call last):
  File "/Users/edgarsampson/odoo-14e/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/Users/edgarsampson/odoo-14e/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: write() takes 2 positional arguments but 3 were given
**Expected behavior**
Commission module to work when using Odoo rental module. 
![Screenshot 2021-03-31 at 11 21 53](https://user-images.githubusercontent.com/16874462/113121832-54393000-9213-11eb-8fb1-c8a8ca45b0dd.png)
![Screenshot 2021-03-31 at 11 21 39](https://user-images.githubusercontent.com/16874462/113121839-5602f380-9213-11eb-8376-14c18cdf2043.png)

**Comment by pedrobaeza** [comment]
I don't think the problem is in this module, as the traceback doesn't indicate that.
