### ISSUE TITLE
"Sales commissions" not working with 13ee ?

### ISSUE THREAD

**Issue by agharaafat** [OCA/commission#297]
Hello
i'm using 13 enterprise 
the app is installed and I can see it on Sales and see all fields
but when trying to settlement agent I don't get anything! 0 
is this app not compatible with enterprise?
or I cant settle manually and should be waiting a month?

**Comment by pedrobaeza** [comment]
The settlement date in the wizard should be higher than the latest invoicing period.

Closing as answered. If not, please specify more details.

**Comment by agharaafat** [comment]
thank you, i got it :)
i have another question please 
there's any way to assign the agent automatically based on the product?
i mean when add product "x" to the order line assign (jone) , when add product (y) assign (zee) ..etc

**Comment by pedrobaeza** [comment]
No. There are several PRs with a module `sale_commission_product`, but they are not completed.

**Comment by agharaafat** [comment]
you mean if this app upgraded from v8 to v13 it's will work? or there are other issues?
https://apps.odoo.com/apps/modules/8.0/sale_commission_product/

**Comment by pedrobaeza** [comment]
That one is not migrated yet, but only a PR.

**Comment by agharaafat** [comment]
sorry, what the meaning of PR :/

**Comment by pedrobaeza** [comment]
Pull request

**Comment by agharaafat** [comment]
thank you and sorry I'm a beginner :) 
I find this https://github.com/OCA/commission/pull/246/files 
for v12 and I see it's not completed 
so what I should do to let it work on v13? 
can I use the source code of v8 and let a developer edit it to be compatible with v13 ?
or what's your advice?

**Comment by pedrobaeza** [comment]
No, it's not possible to be used. Someone experienced must do the migration to v13.

**Comment by agharaafat** [comment]
Hello again 
i'm just installed odoo 8 with https://apps.odoo.com/apps/modules/8.0/sale_commission_product/ 
I can't find any tabs on product to define agent and percentage!
just the normal way to add agent from sales order 
if you need to check 
http://213.136.87.29:8072/web
username: admin
password: 123
