### ISSUE TITLE
Calculate commission differences between v8 , v10 and v12

### ISSUE THREAD

**Issue by IJOL** [OCA/commission#305]
Hola a todos:

We are users of the commission module since v8, and AFAIK the commission calculation is bugged from v10 onward ( didn't know of other versions ) , what we expected is that the calculations done in v8 in _compute_amount module the various refactoring in the middle , do exactly the same in all versions.. but it seems not the case, and the chain of bugs slowly get bigger from v10 to v12, i'll explain my findings (?? maybe it works at expected by someone but that's not our case ):

in v8 the code can be found at https://github.com/OCA/commission/blob/8.0/sale_commission/models/sale_order.py#L86-L103

As anyone how know can see, the calculations include getting price_subtotal, with and without taxes, to be able to do the calculation for net_amount or gross  amount_base_types

at v10 in https://github.com/OCA/commission/blob/10.0/sale_commission/models/sale_commission_mixin.py#L137-L157
this disappears and a comment about not  trying to calculate commission on sales below standard price, but the final result is to do list_price - standard_price which is at least for me very strange, where are the taxes calculations? how the net_amount for the line without taxes get to be calculated.. no idea.. the gross amount seems calculated correctly is in the else part, only using price_subtotal for the next step..

in v12 is in https://github.com/OCA/commission/blob/12.0/sale_commission/models/sale_commission_mixin.py#L145-L162 , and  things get weirder, the else allowing the correct calculation of at least the gross amount_type, gets lost, so there is not correct commission amount.. 

so i wonder if i'm only overlooking a cow in my eyes or this is definitely weird and a bug of sorts...

I'll try to scratch my own itch and contribute back, but first trying to get the cow out of my eye if it's there...

Thanks for any help, thanks to keep reading to here

**Comment by pedrobaeza** [comment]
Please indicate steps to reproduce, what you expect, and what you get, and in which Odoo version.

**Comment by IJOL** [comment]
A sale order with a 5% commission over net amount, with a net amount
of 1805.88 and taxes of 379.23 , gives in v8 90.29 ( 5% of 1805.88)
and in v10 or v12 33.83 ( which is the 5% of 676.6 ) , we expect the
exact same amount calculated in v8 and v12, it seems 676.6 is the
margin in the sale, which btw is the operation it does in
get_commission_amount

subtotal = max([  0, subtotal - product.standard_price * quantity,])

that in our use case is wrong, should be the net amount calculated
from taxes or alike...

**Comment by pedrobaeza** [comment]
Yes, net amount means that, the margin between sales price and cost price. If in v8 is the way you say, then the bug is in that version. I think "Gross amount" is the amount you need for having 90.29 (5% of 1805.88).

**Comment by IJOL** [comment]
Sorry i assumed the explanation some coworker gave me, it seems to that we
have gross commissions too in the v8 sense, how can we achieve that type of
commissions in v12? this seems to be the real problem..

**Comment by pedrobaeza** [comment]
I think "Gross amount" gets the amount without taxes.
