### ISSUE TITLE
Calculating Commissions in Multicurrency 

### ISSUE THREAD

**Issue by luisovalles** [OCA/commission#306]
When making settlements on invoices in different currencies, the settlement is generated without converting between the currencies, adding the amounts regardless of the currency. totaling an amount that is printed on the invoice without reference to the exchange rate.

**Comment by pedrobaeza** [comment]
Yes, this is a missing feature for now. See https://github.com/OCA/commission/tree/13.0/sale_commission#known-issues-roadmap
