### ISSUE TITLE
[13] sale_commission_pricelist not working with direct invoices

### ISSUE THREAD

**Issue by sergioeix** [OCA/commission#325]
Steps to reproduce:  (by now I have account_invoice_pricelist and account_invoice_pricelist_sale installed to handle pricelist on invoices)
1 - make an invoice and select a partner with agent and add a product from a pricelist with commision and save
2 - check commision in line, Commision is not taken from pricelist
Spected behavior the commision is taken from pricelist like in sale order.

Sometimes invoices are not coming from sale orders and are made directly, then this behavior is not applied. It will be awesome is this will be applied on direct invoices too.
B/R

**Comment by pedrobaeza** [comment]
It's **sale**_commission_pricelist, not **account**. Of course it doesn't work. The pricelist doesn't exist in invoices without such module, so you need to add another glue module for joining both.
