### ISSUE TITLE
[12.0] sale_commission : commission lines for sections

### ISSUE THREAD

**Issue by Olimalt85** [OCA/commission#326]
Hello everyone,

I get commission lines for account.invoice.line with display_type=='line_section'

Way to reproduce : 
1 - Define the field agents for a res.partner
2 - Create sale order with a section line and some products for this partner
3 - Confirm the sale order so it creates an invoice
4 - When the invoice is created, remove the agent of lines of products and create a settlements
5 - When you look at the settlement you can see that the line selected in invoice_line field is the section line with a value of 0$

Even If you don't remove the agents of the other lines you will have a line of commission for this section line

Is this a normal behavior ?

**Comment by pedrobaeza** [comment]
Although they are neutral, as the amount is 0, you can open a PR with the code for not generating them at all, or fund someone to do it.

**Comment by Olimalt85** [comment]
Ok, thank you for you reply ! 
I guess i will just modify the reporting without touching the python code.

**Comment by pedrobaeza** [comment]
Well, you can contribute to OCA with the proper code as a thankful to all you are getting from it, isn't it?

**Comment by Olimalt85** [comment]
Sure , i just added this condition in my reporting view : t-if="l.settled_amount != 0". where 'l' is the name of my foreach loop on the lines of the settlement. 
So it won't show the lines with a value of 0 in the settled_amount field (even if its not a section or note and have 0 in the settled_amount we don't need it in my company).
