### ISSUE TITLE
sale.commission.settlement by invoice date

### ISSUE THREAD

**Issue by felipemotter** [OCA/commission#329]
Hello guys, i'm starting to use this repository in v12.0 but some doubts came in my mind.

If i'm using the commission based in invoice payment, when i set the commission, the sale.commission.settlement.line 's will be grouped by invoice date and not by payment date, is this purposeful or necessary?

In Brazil, it's normal partial payments, when this can take a lot of periods easily. So when the sale.commission.settlement is made, it's common to have a lot of records of this model(one for each period that have paid invoices). For me, this is a little strange and the most readable would be the grouping by payment date.

In addition, we are studying an additional module that would work with the partial payment of invoices and this grouping by invoice date is even messier than the case above.

**Comment by pedrobaeza** [comment]
This is how it works for now, creating multiple settlements for the same period if needed. Any other behavior should be implemented.
