### ISSUE TITLE
Commission for First time Purchase

### ISSUE THREAD

**Issue by Cywaithaka** [OCA/commission#33]
Some companies will give commissions to their agents only for the first time purchase. I suggest you add a check when calculating the base commission. Is this something you would consider adding?

**Comment by pedrobaeza** [comment]
Sorry, but not for now (at least by my part). If anyone can contribute with this enhancement, is welcome to do it. I leave this issue open for anyone wiling to contribute to take it into account, but marked as wishlist.

**Comment by Cywaithaka** [comment]
I also noticed that the settlements wizard does not generate the any settlements in my tests. This is how to recreate the issue:
I created the commission with scope "on his customer sales", 
I then created an agent and assigned the commision type
I created a customer and set the agent under the customer.
However, when I make a sale to the customer, confirm and make payment, the generate settlements wizard does not generate anything. Did I miss a step?

**Comment by pedrobaeza** [comment]
Yes, settlements are generated for due/past periods, not for the current. Select a date in the future that assures you the period is due.

**Comment by Cywaithaka** [comment]
Thanks a lot. Selecting a future date did the trick. Btw, I managed to extend the module to support commissions on first time purchases only. I will share it here as soon as I clean it up. You've been of great help.

Warm regards

**Comment by mileo** [comment]
You could use https://github.com/OCA/sale-workflow/tree/9.0/partner_prospect and create a special commission percent for the first sale.

**Comment by Daniel-CA** [comment]
This issue can be closed.
