### ISSUE TITLE
Commissions for Website Sales

### ISSUE THREAD

**Issue by Cywaithaka** [OCA/commission#35]
module: sale_commission
version: 8.0

**Current behavior**
When a sales order/quotation is created on the backend, the commissions are duly calculated. However, when the same customer places  an order to on the ecommerce shop, commissions are zero.
**Expected behavior**
1.If Customer1 places an order on the website, the commissions should be calculated just like when the  order is placed from the backend.

**Comment by pedrobaeza** [comment]
For now that option is not taking into account, but it would be easy to intercept method that creates the sale order line and inject commission values. Maybe you can contribute with this _website_sale_commission_ module.

**Comment by Cywaithaka** [comment]
I tried extending the _website_product_id_change function in sale_order with no success. 

``` python
class SaleOrder(osv.Model):
    _inherit = "sale.order"
    def _website_product_id_change(self, cr, uid, ids, order_id, product_id, qty=0, line_id=None, context=None):
        res = super(SaleOrder,self)._website_product_id_change(cr, uid, ids, order_id, product_id, qty=qty, line_id=line_id, context=None)
        line = self.pool.get('sale.order.line').browse(cr, SUPERUSER_ID, line_id, context=context)
        res['commissions'] = line._default_commissions()
        return res
```

Since the function that populates the commissions is called as a default value, could there be a reason why this default does not apply when the sale order line is created from the website? That is, using the sale_commission module as it is.

**Comment by pedrobaeza** [comment]
I think it should be `line._default_agents`, but I haven't tried.

**Comment by Cywaithaka** [comment]
I have created a repo for the module here https://github.com/Cywaithaka/website_sale_commission/tree/master. Hope we can have other people to contribute. What I have tried so far has not worked.

**Comment by Cywaithaka** [comment]
Hi @pedrobaeza Apologies, I was using @savoirfairelinux branch (8.0_sale_commission_multiple) from here https://github.com/savoirfairelinux/commission/tree/8.0_sale_commission_multiple/sale_commission and I notice there are some naming differences with the main branch. This is why I used line._default_commissions

**Comment by pedrobaeza** [comment]
Closing the same as the PR as explained there.
