### ISSUE TITLE
Purchase commission

### ISSUE THREAD

**Issue by francescapenso** [OCA/commission#366]
There is a module that manages the commissions on purchases (purchase orders and purchase invoices) and worksin the same way as the one on sales commissions even with formulas?

**Comment by pedrobaeza** [comment]
Not yet. The idea is to extract from `sale_commission` a base `commission` module, and over it, put the purchase part, but the split is yet not finished in #363

**Comment by francescapenso** [comment]
This only for 15.0 version or some one is working in 14?

**Comment by pedrobaeza** [comment]
No work for v14 and can't be extracted as stability policy.

**Comment by francescapenso** [comment]
Ok i can understand. And for #363 development there is a forecast?

**Comment by pedrobaeza** [comment]
It seems stuck as formally is not correctly executed. You can ask in such PR.

**Comment by pedrobaeza** [comment]
From 15.0, this is possible to be done as the module was refactored.
