### ISSUE TITLE
Commission defined at the sales order, not just the sales order line

### ISSUE THREAD

**Issue by PopCultureSoft** [OCA/commission#420]
**Is your feature request related to a problem?**
If we want to define commission at the sales order level, we have to add it o each line of the sales order. (There are various reasons we do not want to define the commission at the customer level.) We often have 100 line sales orders, and it would be tedious to change them all manually.

**Describe the solution you'd like**
There should be a place to define the commission for the entire sales order, and have that apply to every line automatically. This would override the commission defined at the customer level.

**Describe alternatives you've considered**
I suppose we could write a server action to take the commission from the first order line and copy it to the subsequent lines. Or we could temporarily change that sales reps commission, then write the sales order, and then set it back.

**Additional context**
Of course, I may just not be understanding how the module works, and this functionality could already be there.

**Comment by pedrobaeza** [comment]
Commissions are set at partner level, and they are just set on each sales order line you create since then, so not very needed to set another on that specific sales order that leads to your need.

**Comment by PopCultureSoft** [comment]
We have a scenario where a partner doesn't have a pre-determined agent, and each sales order could have a different agent. The sales orders could have 100+ line items.

In general, if you need to override the commission on the sales order, and there are 100 line items, it is cumbersome to go edit each sales order line. It would be beneficial to make that sort of change on the sales order itself, and have that update all 100 order lines.

**Comment by pedrobaeza** [comment]
Well, in that case, better that you develop such commodity, and even better if you contribute it back to OCA.
