### ISSUE TITLE
Not computing agent commission (settle commissions command)

### ISSUE THREAD

**Issue by denck** [OCA/commission#430]
## Module
Sales Commissions [https://odoo-community.org/shop/sales-commissions-2239?search=commissions&order=total_download_count+desc&maturity=mature&version=15#attr=8345]

## Describe the bug
Doesn't compute the commissions for the agent.

## To Reproduce
**Affected versions**: v13

1. Created an internal user name "Test salesman"
2. Checked the "agent" on Contacts > Test salesman
3. In Sales > Commissions Management > Agents > I can see that the Agent "Test salesman" is indeed added
4. Created a Commission type for a "fixed percentage" on "payment based"
5. Created a Sales Order > Booked the invoice and booked it as paid
6. Sales > Commissions Management > Settle Commissions > added the date (end of this month for example) and "Test salesman".

**Expected behavior**
It should show an overview of the earned commissions of "Test salesman", but it doesn't. Am I doing something wrong?

**Comment by pedrobaeza** [comment]
Have to put a date after the first settlement period.

**Comment by denck** [comment]
If I created the sales order and payment on for example 29th of May 2023 and I put the settlement period on 31st of May 2023. Isn't that correct? I just tried it and put the settlement date on 30th of June 2023 and still no results.

**Comment by pedrobaeza** [comment]
The settlement date should be the 1st of June

**Comment by denck** [comment]
I must be doing something wrong I think. I recorded a video, maybe this helps to see what I'm doing wrong?
[https://drive.google.com/file/d/162DPYpU1TfYUkSmwLrrd05K7vsx9xv9r/view?usp=share_link](url)

**Comment by pedrobaeza** [comment]
You are not showing in the video how you define the commission. If it's after payment, your invoice is "In payment", not "Paid".

**Comment by denck** [comment]
I do show. It's on 2:30 and it's set on "payment based". On 2:20 I register the payment also so the invoice is paid.

**Comment by pedrobaeza** [comment]
I can't say, but you can check in runboat that is working (user: admin, password: admin).

Invoice: http://oca-commission-13-0-0bd000c792ff.runboat.odoo-community.org/web#id=9&action=222&model=account.move&view_type=form&cids=&menu_id=120
Settlement: http://oca-commission-13-0-0bd000c792ff.runboat.odoo-community.org/web#id=2&active_id=2&model=sale.commission.settlement&view_type=form&cids=1&menu_id=186

**Comment by denck** [comment]
If I change the commission settlement to "invoice based", it does work. So it has to do something with the "payment based" option that is not working in my case.
