### ISSUE TITLE
Sales Commissions wont calculate

### ISSUE THREAD

**Issue by ChukwurahAnthony** [OCA/commission#437]
## Module
Sales commissions

## Describe the bug
Sales Commissions will not compute.

## To Reproduce
**Affected versions**:
V13 Sales commission 13.0.1.8.0
1. Create Agents. Type is default External Agents
2. Create Commission Types and Assign Agents to them
3. Create Sales Order then add agents. Commissions section remains 0.00
4. Confirm Sales Order Commissions section remains 0.00
5. Create invoice and view invoice Commissions section remains 0.00
**Expected behavior**
I expect the commission section to calculate and show the commission
when selecting agents i expect the Commission Amount field to display percentage. It displays 0
<img width="922" alt="commision2" src="https://github.com/OCA/commission/assets/138235660/d39e108e-e95e-4d29-b1d1-f0915254efb3">
<img width="956" alt="commison3" src="https://github.com/OCA/commission/assets/138235660/529c7118-e8b9-4902-9306-344d9dc24cee">
<img width="960" alt="commission" src="https://github.com/OCA/commission/assets/138235660/67ca69fc-2716-4635-8fa3-e752b50a9752">

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by pedrobaeza** [comment]
Please try on a runboat instance, as this may be a bad interaction between modules on your instance.

**Comment by ChukwurahAnthony** [comment]
Please show me how

**Comment by pedrobaeza** [comment]
Check some documentation:

https://odoo-community.org/blog/news-updates-1/goodbye-runbot-welcome-runboat-116
https://odoo-community.org/resources/review
https://www.sygel.es/blog/blog-de-sygel-2/utilizar-odoo-en-runbot-y-runboat-de-oca-46# (in Spanish)
