### ISSUE TITLE
Issue with sale commission in Portal View

### ISSUE THREAD

**Issue by diiman2000** [OCA/commission#45]
Hi,
There is an issue with the sale commission module in portal view.
Here is the process, a customer is given portal access to see their invoices and sale orders but they are unable to see the document due to access right error.
On sale order the error is coming from (Document Module sale.order.line.agent) and 
On Invoices its coming from (Document module account.invoice.line.agent).

Also if these errors where not there and a customer can see the agent commission on their accounts, i think that will be super wrong as well. I suggest the agent commission is somehow removed from the portal documents of the customer r blocked in a way the details are not shown to the customer.

Please see attached screenshots for the error.
![account error](https://cloud.githubusercontent.com/assets/5080681/11644273/86ea7138-9d42-11e5-9030-3fe7220d0fd8.png)
![sale order error](https://cloud.githubusercontent.com/assets/5080681/11644278/8fb4eaa0-9d42-11e5-81ab-1a96c2581911.png)

**Comment by pedrobaeza** [comment]
There can be 2 solutions:
- Put the views that add commission stuff to invoices marked with the group that has the permissions.
- Add the corresponding permissions on portal users.

I think the best is the first one.

**Comment by diiman2000** [comment]
A screenshot of your suggestion will be appreciated or a workflow as your answer above is a bit vague for a novice like me to understand .

**Comment by pedrobaeza** [comment]
Sorry, but it's not intended for a novice, but a guide to any technician that wants to fix it.

**Comment by pedrobaeza** [comment]
Closing as this has changed enough in most modern versions and nobody did it.
