### ISSUE TITLE
Access error. Document type: res.users on res.partner form

### ISSUE THREAD

**Issue by fernandomr** [OCA/commission#46]
After installing the modules: sale_commission, hr_commission and sale_stock_commission:
When first accessing a partner, everything goes ok. But after trying to update a partner, I'm no longer able to access it.
I've tried modifying the users group permissions to specifically allow access to the res_users relation.
Tried also adding the sales groups, like "managers" or "see your leads" directly into the groups tab on the view_partner_form_agent_hr definition.
And at the end, disabled some security rules that might be on the way.
But still, nothing, still can't access partners.

Only Administrator can access the partners now.
I'm on a multi company environment.

**Comment by pedrobaeza** [comment]
Are you using admin?

**Comment by fernandomr** [comment]
No.
And the user is under one company branch

**Comment by pedrobaeza** [comment]
Well, we haven't found this issue working in a multi-company environment. Try to reproduce the bug on runbot and put the steps followed here.

**Comment by pedrobaeza** [comment]
Closing as no more answer.
