### ISSUE TITLE
Sales Commission: Settlements based on Sale Order (not needed Invoice)

### ISSUE THREAD

**Issue by maksymkv25** [OCA/commission#462]
**Is your feature request related to a problem?**
I want to know the commission of the Sales Person before the Invoice is created.

**Describe the solution you'd like**
Add additional settlement type: Sales Orders. "Make settlement" process can create settlements based on confirmed Sales Order (without invoice)

**Additional context**
We can publish it as a separate module or improve the existing Sales commissions module.

**How it works in screenshots
<img width="1701" alt="Знімок екрана 2023-10-13 о 13 33 06" src="https://github.com/OCA/commission/assets/12529036/02cd049a-b565-4ce0-bf06-ac90323464fe">

<img width="1701" alt="Знімок екрана 2023-10-13 о 13 33 42" src="https://github.com/OCA/commission/assets/12529036/6eae6f36-2957-4d3e-be02-249e8e2c74e3">

<img width="1701" alt="Знімок екрана 2023-10-13 о 13 34 07" src="https://github.com/OCA/commission/assets/12529036/ecc48be2-f3f6-4a74-b0d9-528f50987b3e">

**

**Comment by pedrobaeza** [comment]
What about creating instead a report (SQL view) coming from sales order commission lines to get such amounts?

**Comment by maksymkv25** [comment]
Do you mean an additional report based not on `commission.settlement` model but on all confirmed Sales Orders with agent commissions?

**Comment by pedrobaeza** [comment]
Yes, that can be an option. Mention also for which version do you plan to do it.

**Comment by maksymkv25** [comment]
I need to think about your proposal for the new report.
For `16v`

**Comment by pedrobaeza** [comment]
OK, it can be call `forecast` or similar, and even have data for already invoiced quantities.

**Comment by maksymkv25** [comment]
@pedrobaeza It would be better for the user to see lines in UI without printing reports and it would be clearer for the perception, what do you think about it?

**Comment by pedrobaeza** [comment]
A "report" is not a PDF, but an SQL view showing things in a pivot table. Examples of this are "Sales analysis", "Invoice analysis", etc.

**Comment by maksymkv25** [comment]
we cover the case when the user would be able to choose from which document to calculate the commission. For example, product A in the sale order has a price of $100 and in the invoice the price is $80 with the same commission of 10% and the user wants to choose the commission from the sale order

**Comment by pedrobaeza** [comment]
OK, as you prefer.
