### ISSUE TITLE
error in form view sales_order with unit of measure

### ISSUE THREAD

**Issue by MiguelMachadoM** [OCA/commission#49]
@pedrobaeza 
When add 3th line in a sale quotation I recibe following errors:

![commision1](https://cloud.githubusercontent.com/assets/7348561/12086197/0655f33a-b2c8-11e5-9b80-c3afedc205cc.PNG)

And next when try again:

![commision2](https://cloud.githubusercontent.com/assets/7348561/12086205/14af2258-b2c8-11e5-98f7-346a6653bc6c.PNG)

I've tried uninstalling other modules that affected the view and the error still occurs.

More info: if I remove Agent form customer sheet and create a new quotation this error does not occur.

P.D. to reproduce this error you must add at least 3 lines in the quotation

**Comment by ivantodorovich** [comment]
I've also seen this error. It might be related to https://github.com/OCA/commission/issues/62

**Comment by ivantodorovich** [comment]
https://github.com/OCA/commission/pull/78 will probably solve it.

**Comment by Daniel-CA** [comment]
Tested in a runbot instance and the bug doesn't happen, can be closed.
