### ISSUE TITLE
[16.0][RFC]Use Many2one reference to ease the hook with other modules

### ISSUE THREAD

**Issue by flotho** [OCA/commission#508]
Hi,

Thanks for this awesome repo.
I'm using it and have also tried a POS implementation.
I faced some drawbacks regarding the way the relation is described here : https://github.com/OCA/commission/blob/16.0/commission/models/commission_mixin.py#L108

Due to this implementation, each time we want to add a new settelemnt type base on something.line.agent we have to add a new field . Of course it works but also implies to change the reporting and break genericity.

@pedrobaeza , do you think that it could be a proper way to improve the genericity here ?

Thanks for your feedback.

Regards

**Comment by pedrobaeza** [comment]
I don't have any clue right now except overwriting `object_id` with the corresponding type.
