### ISSUE TITLE
What is a "manual" settlement? 

### ISSUE THREAD

**Issue by PopCultureSoft** [OCA/commission#509]
module: sale_commission
version: 16.0

Can I get more information on what a "manual" settlement_type is, and how you envision it working? Or be pointed to the documentation on it?

I figured it is for when I don't want a settlement line to automatically get created when I create settlements, but they get created anyway. 

Basically, both "manual" and "sales invoices" seem to have the same behavior.

**Comment by pedrobaeza** [comment]
The difference is that a manual settlement doesn't allow to generate a vendor bill.

**Comment by PopCultureSoft** [comment]
That is not what I am experiencing. I created a commission type with a settlement type of Manual. I created a sales order, and applied this commission to a sales order line. I settled commissions, and this line appeared in a settlement. Then it let me make a vendor bill.

**Comment by pedrobaeza** [comment]
The settlement type should match on automatic commission mappings. If you set it manually, then it's normal that it allows you to do some weird things like that.
