### ISSUE TITLE
Refound invoice no set agent 

### ISSUE THREAD

**Issue by MiguelMachadoM** [OCA/commission#51]
@pedrobaeza 
when you create a refund from a invoice does not set the corresponding agentin in lines.

![captura](https://cloud.githubusercontent.com/assets/7348561/12169425/9f10676e-b538-11e5-9832-2ac2b5aab474.PNG)

**Comment by pedrobaeza** [comment]
Solved in https://github.com/OCA/commission/pull/53

**Comment by ivantodorovich** [comment]
Should this be closed?

**Comment by pedrobaeza** [comment]
Yes
