### ISSUE TITLE
button fa-users not showing in order lines

### ISSUE THREAD

**Issue by DanNetoffGit** [OCA/commission#510]
## Module
sale_commission

## Describe the bug
Same bug in 14.0 and 15.0 odoo`s
File https://github.com/OCA/commission/tree/16.0/sale_commission/views/sale_order_view.xml
button  - invisible - bad domain: 'invoice_lines' need change to order lines, not invoice

<button
                    name="button_edit_agents"
                    title="Edit agents"
                    icon="fa-users"
                    attrs="{'invisible': ['|', ('commission_free', '=', True), ('invoice_lines', '!=', [])]}"
                    type="object"
                />

## To Reproduce
**Affected versions**:

1. install, create new order, select any product - button not shown

**Comment by pedrobaeza** [comment]
You have to save for having access to the button.
