### ISSUE TITLE
Refund invoices settlements should be 'negative'

### ISSUE THREAD

**Issue by ivantodorovich** [OCA/commission#55]
Even though `account.invoice.commission_total` is correct (ie: $ -10), when settling the `sale.commission.settlement` is incorrect (positive sign --> ie: $ 10), hence paying the agent twice for something it shouldn't have been paid.

**Comment by ivantodorovich** [comment]
I believe it's considered here `account.invoice._compute_commission_total`:

``` python
# Consider also purchase refunds, although not in the initial scope
if record.type in ('out_refund', 'in_refund'):
      record.commission_total = -record.commission_total
```

But nowhere else (that I can find).

`sale.commission.settlement.line.settled_ammount` doesn't hold any values, but instead relates to `account.invoice.line.agent.amount`

**Comment by pedrobaeza** [comment]
You're right. The best is to put the negative on the lines, so in the settlement it appears automatically correct. The only check you should do is if the total is negative (because there are more refunds than invoices), the invoice to create should be a refund.

Can you make a PR with that?

**Comment by pedrobaeza** [comment]
OK, I see now the PR, hehe. Then change according comment about the invoice creation, but I see that you have also thought about the same method :wink:
