### ISSUE TITLE
'installable': False is set in the sale_commission manifest file in 9.0 branch

### ISSUE THREAD

**Issue by nicholas-itpedia** [OCA/commission#59]
Does this mean this code is not released for 9.0? Is this an oversight? Should it be changed t     'installable': True ? What else needs to be done in order to make this 9.0 compatible and stable enough for production use?

**Comment by pedrobaeza** [comment]
Yes, it's not yet migrated, but I'm on it. Expect it on 2 weeks.

**Comment by nicholas-itpedia** [comment]
Thanks for the update. Is there anything we can help with?

**Comment by pedrobaeza** [comment]
You can make testing when done. I'll ping you then.
