### ISSUE TITLE
[sale_commission] Commissions are not being settled for invoices duplicated from a settled invoice.

### ISSUE THREAD

**Issue by ivantodorovich** [OCA/commission#61]
1. Create an invoice with agent lines
2. Settle the invoice from the commissions wizard
3. Duplicate the invoice
4. Try to settle de invoice

Result: Invoice is ignored in the settlement.
Expected: Invoice commission should be settled.

This bug won't occur, though, if the invoice is duplicated from a not settled invoice.

I'm guessing the `account.invoice.line.agent`'s `settled` field is being copied aswell when duplicating an invoice, hence ignoring this invoice line from settlements.

Is there a way to avoid this? a way to reset this field value when duplicating?
I don't know how to do it, yet, at least not without investigating the web for a few hours.

**Comment by pedrobaeza** [comment]
You  can set `copy=False` in the field definition to avoid it.

**Comment by ivantodorovich** [comment]
``` python
settled = fields.Boolean(compute="_compute_settled", store=True, copy=False)
```

What about the other `account.invoice.line.agent` fields, like `invoice_line`, `invoice`, `invoice_date`. Should they be set to `copy=False`, too?

**Comment by pedrobaeza** [comment]
They are automatically linked to the new records, so they are not needed.
