### ISSUE TITLE
Error installing sales_co....

### ISSUE THREAD

**Issue by singleroot** [OCA/commission#65]
Hello, 

When installing Im getting:

openerp.addons.base.ir.ir_ui_view: El elemento '<xpath expr="//field[@name='invoice_line']/tree//field[@name='price_subtotal']">' no puede ser localizado en la vista padre

Error de contexto:
Vista `account.invoice.form.agent`
[view_id: 1552, xml_id: n/a, model: account.invoice, parent_id: 470]" while parsing /home/singleroot/erp-prod/odoo/addons/sale_commission/views/account_invoice_view.xml:29, near
<record id="invoice_form_agent" model="ir.ui.view">
            <field name="name">account.invoice.form.agent</field>
            <field name="model">account.invoice</field>
            <field name="inherit_id" ref="account.invoice_form"/>
            <field name="arch" type="xml">
                <data><field name="invoice_line" position="attributes">
                    <attribute name="context">{'partner_id': partner_id}</attribute>
                </field>
                <xpath expr="//field[@name='invoice_line']/tree//field[@name='price_subtotal']" position="after">
                    <field name="commission_free"/>
                    <field name="agents" attrs="{'readonly': [('commission_free', '=', True)]}"/>
                </xpath>
                <field name="amount_total" position="after">
                    <field name="commission_total" widget="monetary" options="{'currency_field': 'currency_id'}"/>
                </field>
            </data></field>
        </record>

**Comment by Daniel-CA** [comment]
Lack of information, there is no way to replicate this error, this issue can be closed.
