### ISSUE TITLE
Problem with supplier invoice number

### ISSUE THREAD

**Issue by antone-colonna** [OCA/commission#68]
Hello

I have a problem with supplier invoice number. When i generate invoices from settlements, supplier invoice number is the same that client invoice number.

Do i something wrong ?

**Comment by pedrobaeza** [comment]
This set of modules doesn't support supplier invoices, so I don't get you. Are you referring to the generated supplier invoice for the agent?

**Comment by antone-colonna** [comment]
Yes

**Comment by antone-colonna** [comment]
Yes it's about the supplier invoice for the agent. Can we change the number by another

ex: client invoice number SAJ/2016/001
agent supplier invoice EXJ/2016/001

**Comment by pedrobaeza** [comment]
That depends on the sequence associated to your supplier journal, so it's not a problem of the module.

**Comment by antone-colonna** [comment]
Oh sorry you're right, it's ok with the good journal :-)

Thanks
