### ISSUE TITLE
Get in agent invoice in purchase the origin client invoice number

### ISSUE THREAD

**Issue by antone-colonna** [OCA/commission#69]
Hello 

Just a question to upgrade the module. How to add in agent invoice the client invoice number ?

In settlement.py we have function prepare_invoice_header

`def _prepare_invoice_header(self, settlement, journal, date=False):
        invoice_obj = self.env['account.invoice']
        invoice_vals = {
            'partner_id': settlement.agent.id,
            'type': ('in_invoice' if journal.type == 'purchase' else
                     'in_refund'),
            'date_invoice': date,
            'journal_id': journal.id,
            'company_id': self.env.user.company_id.id,
            'state': 'draft',
        }
`

after             'state': 'draft',

Can we add something like 'origin': invoice.id or invoice.number ??

**Comment by pedrobaeza** [comment]
You can use origin field that is a text for indicating the source document.

**Comment by antone-colonna** [comment]
Ok but how paste in origin the client invoice number. 

can i call directly invoice_id or invoice.id??

I never use python code :(

**Comment by pedrobaeza** [comment]
No, because there's a lot of invoices that can make a supplier invoice. Sorry, but this is out of scope of the purpose of issues.
