### ISSUE TITLE
Steps to 'Make it totally multi-company aware.' (it's in the roadmap)

### ISSUE THREAD

**Issue by ivantodorovich** [OCA/commission#73]
Our business is using a two-company enviorment.

We need to settle commissions from sales of the 2 companies, but create the invoice only in one of them.

I intend to develop this feature, and since I'm at it, I'd like to know your thoughts/needs regarding what should be implemented to make this module 'totally multi-company aware'.

**Should the settlement wizard ask the company of the sales to settle?**
For instance, settle only invoices from company A.
Or add an option to settle invoices from all companies, or maybe select which companies (Many2Many)

**Should the invoice wizard allow to..**
_A)..make settlement invoices in the company where the sale was invoiced?_
_B)..same as above, but selecting which companies' settlements to invoice_
_C)..make all settlement invoices in a selected company?_ (fyi, this is what I need)

**Comment by pedrobaeza** [comment]
In fact, for what you want there's no need to make any changes, because it's already supported out of the box, while you use a user different from admin.

What it's needed for full multi-company support is to make commission field company dependent and several things in the same way.
