### ISSUE TITLE
[BUG?] Editing the commision will recalculate all previous agent lines and settlements.

### ISSUE THREAD

**Issue by ivantodorovich** [OCA/commission#76]
Editing a `sale.commission` that's already in use will trigger an update on every existing invoice, sale order, and settlements that were using that commission "rule".

This is because of `@api.depends`:

``` py
    @api.depends('commission.commission_type', 'invoice_line.price_subtotal',
                 'commission.amount_base_type')
    def _compute_amount(self):
```

I think this could cause consistency errors.

IMO, settled invoices's commissions (agent lines) should remain unchanged, even if the `sale.commission` percentage / formula / rule changes.

One could argue that it shouldn't even change on unsettled invoices / sale orders. IE: If an agent renegotiates it's commission percentage, the change should apply on new sales, not previous ones.. even if they are not settled yet.

What do you think?

Should we remove `'commission.commission_type'` and `'commission.amount_base_type'` from the `@api.depends`?

**Comment by pedrobaeza** [comment]
Yeah, you're totally right about that depends. Please make a PR removing it.
