### ISSUE TITLE
Error: QWeb2 - template['ListView.row']: Runtime Error: Error: Unknown m2m command 0

### ISSUE THREAD

**Issue by mileo** [OCA/commission#81]
Hi,

The last update on sale_commission breaks sale order and invoice lines view.

How to reproduce: 

Login or any other instance http://3144043-8-0-f3c950.runbot2.odoo-community.org/web?db=3144043-8-0-f3c950-all#view_type=form&model=sale.order&menu_id=316&action=403

1- Configure some costumer with a default agent.
2- Create a new sale order with this costumer;
3- After add a new item:

![captura de tela de 2016-03-21 11 22 26](https://cloud.githubusercontent.com/assets/1975978/13921566/385b670e-ef57-11e5-9e6b-3e5f0776bd97.png)

**Comment by ghost** [comment]
@mileo  am facing same issue have you found any solution ?

@pedrobaeza Can you please help to fix this issue ?

Thanks in advance.

**Comment by pedrobaeza** [comment]
This is solved in the last version with the inclusion of https://github.com/OCA/commission/pull/78. Please check now.

**Comment by hbrunn** [comment]
actually, the problem has nothing to do with this widget, it's caused by https://github.com/odoo/odoo/pull/11282#issuecomment-204538025

**Comment by pedrobaeza** [comment]
Thanks for the tip. I thought it was something with the widget.

**Comment by codingforfun** [comment]
@mileo 
I try to reproduce this, since https://github.com/odoo/odoo/pull/11282 was made by me and has been identified as the cause for your problem by @hbrunn. However I can't reproduce from your description. The link isn't working and I can't find what you mean by `default agent`. Is this specific to `sale_commision` module? Where do I find this? 
Normal sale order creation seams to work fine for me.

**Comment by mileo** [comment]
@MeetSCS @codingforfun

Fixed with #78

Tested with:
https://github.com/OCA/web/commit/fc38550429e6718f0d13b2e883726aa231c9ca09
and 
https://github.com/OCA/OCB/commit/17d056a59bc902182da65af17a3d73fac49ffd0b

**Comment by ghost** [comment]
@mileo @pedrobaeza @hbrunn Thanks a lot guys !!
