### ISSUE TITLE
Error on Sale Commission Module, can not add a second SO line. TypeError: Cannot read property 'constructor' of undefined

### ISSUE THREAD

**Issue by jjscarafia** [OCA/commission#82]
Steps to reproduce (tested on runbot and local):
1. log in with admin
2. Go into quoatations menu / enter SO "SO003"
3. Enter partner "Chamber Works"
4. Assign "Agents" with "agent 1", save and go back to sale order
5. Click on "add an item", choose "ice cream", without saving click on "Add an item", you should get an error with "TypeError: Cannot read property 'constructor' of undefined"

I have try to investigate the issue but haven't found so much. It is related to the o2m editable inside the o2m editable of sale order lines. If you make sale order lines open in a form, it works ok.

Console log:

> instance.web.FormView.instance.web.View.extend._process_save  @   view_form.js:893
> (anonymous function)    @   view_form.js:619
> (anonymous function)    @   jquery.js:1129
> fire    @   jquery.js:974
> self.add    @   jquery.js:1020
> (anonymous function)    @   jquery.js:1127
> jQuery.extend.each  @   jquery.js:611
> (anonymous function)    @   jquery.js:1123
> jQuery.extend.Deferred  @   jquery.js:1184
> promise.then    @   jquery.js:1122
> iterate @   view_form.js:616
> (anonymous function)    @   view_form.js:632
> (anonymous function)    @   openerpframework.js:1352
> (anonymous function)    @   jquery.js:1129
> fire    @   jquery.js:974
> self.add    @   jquery.js:1020
> (anonymous function)    @   jquery.js:1127
> jQuery.extend.each  @   jquery.js:611
> (anonymous function)    @   jquery.js:1123
> jQuery.extend.Deferred  @   jquery.js:1184
> promise.then    @   jquery.js:1122
> openerp.Mutex.openerp.Class.extend.exec @   openerpframework.js:1351
> instance.web.FormView.instance.web.View.extend._process_operations  @   view_form.js:603
> instance.web.FormView.instance.web.View.extend.save @   view_form.js:823
> instance.web.list.Editor.instance.web.Widget.extend.save    @   view_list_editable.js:773
> (anonymous function)    @   view_list_editable.js:329
> instance.web.ListView.include.with_event    @   view_list_editable.js:406
> (anonymous function)    @   view_list_editable.js:324
> (anonymous function)    @   openerpframework.js:1352
> (anonymous function)    @   jquery.js:1129
> fire    @   jquery.js:974
> self.add    @   jquery.js:1020
> (anonymous function)    @   jquery.js:1127
> jQuery.extend.each  @   jquery.js:611
> (anonymous function)    @   jquery.js:1123
> jQuery.extend.Deferred  @   jquery.js:1184
> promise.then    @   jquery.js:1122
> openerp.Mutex.openerp.Class.extend.exec @   openerpframework.js:1351
> instance.web.ListView.include.save_edition  @   view_list_editable.js:320
> instance.web.ListView.include.ensure_saved  @   view_list_editable.js:198
> instance.web.form.FieldOne2Many.instance.web.form.AbstractField.extend.save_any_view    @   view_form.js:4341
> instance.web.form.FieldOne2Many.instance.web.form.AbstractField.extend.commit_value @   view_form.js:4330
> (anonymous function)    @   view_form.js:610
> (anonymous function)    @   openerpframework.js:1352
> (anonymous function)    @   jquery.js:1129
> fire    @   jquery.js:974
> self.add    @   jquery.js:1020
> (anonymous function)    @   jquery.js:1127
> jQuery.extend.each  @   jquery.js:611
> (anonymous function)    @   jquery.js:1123
> jQuery.extend.Deferred  @   jquery.js:1184
> promise.then    @   jquery.js:1122
> openerp.Mutex.openerp.Class.extend.exec @   openerpframework.js:1351
> (anonymous function)    @   view_form.js:609
> (anonymous function)    @   jquery.js:1129
> fire    @   jquery.js:974
> self.add    @   jquery.js:1020
> (anonymous function)    @   jquery.js:1127
> jQuery.extend.each  @   jquery.js:611
> (anonymous function)    @   jquery.js:1123
> jQuery.extend.Deferred  @   jquery.js:1184
> promise.then    @   jquery.js:1122
> (anonymous function)    @   view_form.js:608
> _.each._.forEach    @   underscore.js:87
> iterate @   view_form.js:607
> (anonymous function)    @   view_form.js:632
> (anonymous function)    @   openerpframework.js:1352
> (anonymous function)    @   jquery.js:1129
> fire    @   jquery.js:974
> self.add    @   jquery.js:1020
> (anonymous function)    @   jquery.js:1127
> jQuery.extend.each  @   jquery.js:611
> (anonymous function)    @   jquery.js:1123
> jQuery.extend.Deferred  @   jquery.js:1184
> promise.then    @   jquery.js:1122
> openerp.Mutex.openerp.Class.extend.exec @   openerpframework.js:1351
> instance.web.FormView.instance.web.View.extend._process_operations  @   view_form.js:603
> instance.web.FormView.instance.web.View.extend.save @   view_form.js:823
> instance.web.FormView.instance.web.View.extend.on_button_save   @   view_form.js:727
> (anonymous function)    @   views.js:1539
> jQuery.event.dispatch   @   jquery.js:3058
> elemData.handle.eventHandle @   jquery.js:2676

**Comment by pedrobaeza** [comment]
This PR solves it: https://github.com/OCA/commission/pull/78

**Comment by jjscarafia** [comment]
Thanks for the response, I close this issue, as is being fixed on https://github.com/OCA/commission/pull/78
