### ISSUE TITLE
I can't seem to get the sales commision to work and settle Agents

### ISSUE THREAD

**Issue by danidee10** [OCA/commission#87]
I've installed this module, created a sales order and attached an agent to the sales order however when i try to make settlements no invoice gets raised. in fact nothing happens at all the dialog just dis appears. i also did a little investigation, the "settle commissions" and "make settlements" button are linked to the wizard/wizard_settle.py which is a TransientModel and is not going to be persisted to the database (if the module works at all the invoice should be created i should be able to see the commission summary when i view the agent at least for some time before odoo cleans it up, but i don't see anything)

i think I'm missing something about how this module should be installed

please can i get a definitive guide on how i can setup this module for the simplest use case to see that it actually makes commissions and raises invoices

**Comment by pedrobaeza** [comment]
Settlements are made over due periods. That's to say, if you make an invoice on 5th of June and your settlement period is monthly, you have to settle from 1th of July and above.

**Comment by danidee10** [comment]
Oh....Thank you very much i actually figured it out this morning. Thanks
anyway
