### ISSUE TITLE
Agents on invoice when invoicing from picking

### ISSUE THREAD

**Issue by aitorbouzas** [OCA/commission#88]
Hi,

Just tested the module sale_commissions, it works nice, but there are too little questions i'd like to ask. 
1. Is there any way to reflect the agents in the invoice when a sale order is invoiced from picking? At the moment I think this is something the module should do (maybe it really does, but for me it is not working, should I configurate something?)
2. Is there any kind of way to see/print a report of settlements without executing the "Settle commission" option? The problem here is that if you settle commissions before the end of the month, it won't increment the actual created settlement's amount in the agent data if you execute it again later...

**Comment by aitorbouzas** [comment]
Question 1 answered in #89

**Comment by aitorbouzas** [comment]
I think it would be nice to have some menu item where to list all the settlements to be able to group them by agent, by month, etc.
Or maybe some kind of way to print the settlements of a period.

It would be really helpful, too, to have some report or some method to check how much will be settled in a period without settling them...

**Comment by pedrobaeza** [comment]
For 2, remove the settlement and make it again.

The feature yo say is nice, but needs someone to do it. If you want...

**Comment by aitorbouzas** [comment]
Ok,

I'm working on adding a menuitem and a qweb report for settlements.

**Comment by pedrobaeza** [comment]
Better to have an analysis view than a qweb report.

**Comment by aitorbouzas** [comment]
Isn't there already one?

**Comment by pedrobaeza** [comment]
I'm afraid not. Closing to continue on the PR.
