### ISSUE TITLE
Commission based on product category

### ISSUE THREAD

**Issue by elicoidal** [OCA/commission#97]
Hi,
I have a customer who has commission based on product category. 
Would you welcome a PR or new module that would define a percentage on product category and set the commission type "Product Category based"?
Thanks for your feedback

**Comment by pedrobaeza** [comment]
@elicoidal, maybe this can help: https://github.com/OCA/commission/pull/95

If not, an improvement over sale_commission_product would be welcome.

**Comment by elicoidal** [comment]
@pedrobaeza thanks. I will have a look

**Comment by pedrobaeza** [comment]
Closing as there are PRs for commissions at product level.
